### ISSUE TITLE
Lab 10 - Lab updates

### ISSUE THREAD

**Issue by soccerjoshj07** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#174]
Exercise 1:
> Task 2: Activate Azure AD Premium v2 trial
> 1. In the Azure portal, set the Directory + subscription filter to the newly created Azure AD tenant.
> 
> Note: The Directory + subscription filter appears to the right of the Cloud Shell icon in the toolbar of the Azure portal
> 
> Note: You might need to refresh the browser window if the AdatumLab101-4b entry does not appear in the Directory + subscription filter list.
> 
> 2. In the Azure portal, navigate to the AdatumLab101-4b - Overview blade.
> 
> 3. From the AdatumLab101-4b - Overview blade, navigate to the Licenses - Overview blade.
> 
> 4. From the Licenses - Overview blade, navigate to the Licenses - All products blade.
> 
> **5. From the Licenses - All products blade, navigate to the Activate blade and activate Azure AD Premium P2 free trial.**

For step #5, to get to the Azure AD Premium P2 free trial, you have to click the "**Try / Buy**" button and then activate the free trial.

**Comment by polichtm** [comment]
Appreciate the suggestion - but the intention is to avoid "click on" type of instructions, since this would significantly increase maintenance overhead due to frequency of changes to the Azure portal interface 
The above instructions are accurate (you do need to navigate to the Activate blade) - and leave it to students to explore the interface to identify the intermediate step. The goal is to promote the learning experience. Obviously students can also refer to you for help if needed.
Hope this makes sense - let us know if any additional clarification is needed
rgds
Marcin

**Comment by soccerjoshj07** [comment]
Fair. With all of the recent AAD changes I thought lab 10a was the choppiest to follow, but I understand your wanting to not over document everything. Cheers

**Comment by polichtm** [comment]
To clarify - we want to make sure that the instructions are accurate but not unnecessarily detailed - yet at the same time, sufficiently clear ;)
This tends to be a challenging combination - so your feedback is always welcome
rgds
Marcin
