### ISSUE TITLE
Module 11b - Task 4 - Step 11 - Validation did *not* fail.

### ISSUE THREAD

**Issue by heshtur** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#231]
After implementing the tagging enforcement per instructions, the validation did **not** fail and the deployment proceeded forward; after a while the deployment did actually fail. Validation prior to actually "purchasing" or initiating the deployment did not fail.

I will add, much of the steps in this lab leave out a lot of "Save the settings and proceed" type of instruction, so I'm assuming its implied (examples Task 2 - Step 4, skips over the "Save" and starts with "From Policy - Definitions..")

The changes made switching the "Create a resource" to "New" is also incorrect; it does not say "New" and still remains "Create a resource." (examples: every time the **New** blade is mentioned.)

**Comment by polichtm** [comment]
Hi Christopher,
pls post the error associated with the failed deployment.
Regarding your second comment, some of the (more obvious) steps are implied in order to minimize maintenance overhead. Do you feel it is necessary to point out that changes made throughout provisioning tasks should be saved?
As far as the third comment is concerned, this has been take care of
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
