### ISSUE TITLE
LAB 6, Having an issue with creating SQL/Servers 

### ISSUE THREAD

**Issue by DiamondLee88** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#245]
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "ProvisioningDisabled",
                "message": "MSDN subscriptions are restricted from provisioning in this region. Please choose a different region. For exceptions to this rule please open a support request with Issue type of 'Service and subscription limits'."
            }
        ]
    }
}

I have tried many different regions but got the same errors

**Comment by staleycyn** [comment]
This is most likely due to Microsoft's prioritizing cloud resources for Covid-19. You can read more here - [Update #2 on Microsoft cloud services continuity](https://azure.microsoft.com/en-us/blog/update-2-on-microsoft-cloud-services-continuity/). You can also read more about our efforts to support classroom training on the MCT Courseware Forum.
