### ISSUE TITLE
Module 10 Lab

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#25]
In Module 10 , Exercise 0, we run a template deployment to our Azure default tenant domain that creates a VM.  In Exercise 1, we create a new tenant domain. In Exercise 2, we setup Azure AD Identity Protection IN the new tenant domain. It then wants us to go to the VM that Exercise 0 created. Am I misunderstanding something or this can't work since the VM is in the wrong domain. 

Confused MCT. :)
Jeff Smalley

**Comment by GerardoAttardi** [comment]
Hi Jeff. The fact that the VM is in a different domain does not matter. 

The only part that is missing is that the lab should instruct to SWITCH DIRECTORY to the default directory to be able to "see" the VM...

For the purposes of the LAB you could use ANY VM (even your own computer) to install TOR Browswer and test "Sign IN - Risk Policy" and "User Risk  Policy".

You cannot create the VM in the new tenant becouse you have no subscritption there. Azure Pass Subscription is in the DEFAULT DOMAIN that is why you deploy de VM there.... But AD PREMIUM is activated in the other DOMAIN (AdatumLab101-4b Azure AD tenant).....

I thing this lab is confusing......

Hope it helps......

Gerardo

**Comment by polichtm** [comment]
Hi Gerardo, 
The decision to use a separate Azure AD tenant was based on the need to avoid cross-lab dependencies - additionally, this allows running the lab multiple times (which would not be the case if students were using the default Azure AD tenant. 
You are correct - it is necessary in this case to switch the Azure AD tenant - but the ToR browser can be run from anywhere. In this case, the intention is to avoid installing ToR browsers directly on students' computers.
rgds
Marcin

**Comment by GerardoAttardi** [comment]
Thanks for your answer... I agree with you... Students could not be LOCAL ADMIN in their computers if they are attending the course inside classroom at an MCTP... i find usefull to use a VM (and that VM must be created using de default domain because of the subscription attached to it...) still all this explanation (the one in your comment) would be very useful as a "NOTE" inside the LAB steps to clarify even more the whole scenario.....

It is not straightforward to delete a NEW AD TENANT inside an Azure ACCOUNT (more dificult yet if you have users Synced form ADConnect as in other labs)... so it would be great to have that steps detailed as part of the LAB cleanup process... when students finish the LAB:

1) Remove all RESOURCE GROUPS
2) Remove all Domains.... (except de default domain)

In my case... I am using Azure Pass inside an Azure Account that has many subscriptions..... Azure Pass will expire... BUT the New Domain Tenant... will remain.... and it is annoying to have it forever.

**Comment by JeffSmalley** [comment]
Thanks for the feedback.   My lab now works. (this is assuming that I skip the MFA phone call back and blocking a user part of the lab which isn't available. This is open in another issue. I just used the SMS text option).   I do suggest the lab steps should have the students disable the IE Enhanced Security before going and downloading the TOR browser.   

I also agree we really need steps on all the labs to clean up the lab environment. With adding the extra Tenants it gets complicated to do that. (Module 9, 10, etc.)    

I believe the GitHub tool can be awesome with fixing the labs quickly which I have seen already this week. Great Job!  The challenge is getting the MCTs to report issues so it can be fixed.  This AZ-103 course has been running the last couple weeks plus and just a few of us are participating...  I am not sure if they are uninformed or just unmotivated.  Azure is a changing environment and we need everyone to help with the revisions.

Ciao!

**Comment by polichtm** [comment]
Hi Gerardo and and Jeff,
for instructions describing the process of deleting an Azure AD tenant, refer to https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-delete-howto.
I'll make sure that this reference is included in the lab instructions
rgds
Marcin

**Comment by GerardoAttardi** [comment]
Hi Marcin. Thank you for your reference to https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-delete-howto.

I am aware of the steps detailed there.

I am MCSE, MCSA, MCT, VCP, AAI, and I have been delivering Microsoft courses since 1998. I am the oldest MCT in Argentina (not because of my age... but because I have been delivering courses for more than 20 years)

The REAL NEED of that steps in lab instructions is for STUDENTS.

Labs cleanup should be a Script (I know..... the script needs to be updated as well, very fast, as Azure changes....).

LABS need to be every time smoother, clearer, complete, self explanatory, professionally designed, accurate and updated to the real azure portal interface ...

In my opinion, it is not correct to tell Students.... "If you want to remove lab contents inside your subscriptions... go to Microsoft DOCS and read how it is done.... ) or.... "If the portal is different as described in lab steps..... well.... look around and you will find the configuration option nearby.... or ask the trainer, he or she will know..." It is very frustrating for students, believe me. They waste a lot of time because of this.....

In my opinion and expertise, students are not happy with this "LABSMESS" around AZURE courses since the beginning (for example 20533 courses)..... 

I am telling this with respect. I love my Job, I love Microsoft world  and Students are my priority.

**Comment by staleycyn** [comment]
Gerardo - This public GitHub repo is for distributing lab instructions to MCTs. Your comments and opinions on the courseware should be posted on the MCT Courseware forum. Thank you.

**Comment by GerardoAttardi** [comment]
Mi mistake then...

Thanks for your help

**Comment by staleycyn** [comment]
To be clear, any specific issues with the labs steps can be addressed here. So, other MCTs will know what to look for.  But, if you wish to discuss or offer opinions on the quality of the courseware or improvements to the courseware, then I look forward to seeing you in the MCT Courseware Forum. Thank you for your feedback.

**Comment by GerardoAttardi** [comment]
Thank you Staleycyn, you have been very clear, I really appreciate your words. I will be there at MCT Courseware Forum always trying to help to improve and share opinions. My  motivations are always positive and respectful.

For now on, I will only post technical questions about the labs steps here. 

Your help is really valuable for all MCT community. I mean it. Thanks a lot

**Comment by polichtm** [comment]
udpated
